<?php
$carouselItems = [
  [
    'image' => 'assets/bohol.webp',
    'title' => 'BOHOL',
    'description' => 'Provides a fantastic mix of natural wonders and cultural sites. Must-sees include the unique Chocolate Hills and Philippine tarsiers, along with beautiful beaches, the Loboc River cruise, and historical churches.'
  ],
  [
    'image' => 'assets/login-sample.jpeg',
    'title' => 'EL NIDO',
    'description' => 'The "crown jewel" of Philippine tourism, offering unparalleled natural beauty with breathtaking limestone landscapes, crystal-clear waters, and incredible island hopping. El Nido boasts stunning lagoons and beaches, while Coron is famous for wreck diving and unique lakes.'
  ],
  [
    'image' => 'assets/boracay.jpg',
    'title' => 'BORACAY',
    'description' => 'World-famous for its powdery White Beach and vibrant atmosphere. It\'s a top spot for relaxation, water sports, and lively nightlife, known for its accessibility and concentrated beauty.'
  ],
  [
    'image' => 'assets/destinations/siargao.jpeg',
    'title' => 'SIARGAO',
    'description' => 'The surfing capital of the Philippines, home to the legendary Cloud 9 wave. Experience world-class surfing, pristine beaches, crystal-clear lagoons, and the famous Sugba Lagoon. Perfect for adventure seekers and water sports enthusiasts.'
  ]
];

$destinations = [
  [
    'image' => '/assets/destinations/cebu.jpg',
    'package' => 'Cebu Explorer Package',
    'location' => 'Cebu, Lapu-Lapu City',
    'url' => '/details/cebu',
    'country' => 'Philippines',
    'star' => 4,
    'rating' => 9.2,
    'users_rated' => 156,
    'from' => 'Manila',
    'to' => 'Cebu',
    'price' => 12500,
    'original_price' => 16000,
    'start_date' => 'April 10, 2025',
    'end_date' => 'April 17, 2025',
    'trip_id' => '214238732',
    'activities' => ['surfing', 'kayaking'],
    'info_needs' => ['transportation', 'weather', 'gear']
  ],
  [
    'image' => '/assets/destinations/siargao.jpeg',
    'package' => 'Siargao Surf Adventure',
    'location' => 'Siargao, General Luna',
    'url' => '/details/siargao',
    'country' => 'Philippines',
    'star' => 5,
    'rating' => 9.8,
    'users_rated' => 203,
    'from' => 'Manila',
    'to' => 'Siargao',
    'price' => 18900,
    'original_price' => 24000,
    'start_date' => 'May 5, 2025',
    'end_date' => 'May 15, 2025',
    'trip_id' => '214238733',
    'activities' => ['surfing', 'kayaking', 'fishing'],
    'info_needs' => ['transportation', 'weather', 'gear', 'activity']
  ],
  [
    'image' => '/assets/destinations/boracay.jpg',
    'package' => 'Boracay Beach Paradise',
    'location' => 'Boracay, Malay Aklan',
    'url' => '/details/boracay',
    'country' => 'Philippines',
    'star' => 4,
    'rating' => 9.5,
    'users_rated' => 289,
    'from' => 'Manila',
    'to' => 'Caticlan',
    'price' => 15500,
    'original_price' => 19500,
    'start_date' => 'June 10, 2025',
    'end_date' => 'June 17, 2025',
    'trip_id' => '214238734',
    'activities' => ['surfing', 'kayaking'],
    'info_needs' => ['transportation', 'weather', 'health']
  ],
  [
    'image' => '/assets/destinations/palawan.jpg',
    'package' => 'Palawan Underground Adventure',
    'location' => 'Palawan, Puerto Princesa',
    'url' => '/details/palawan',
    'country' => 'Philippines',
    'star' => 5,
    'rating' => 9.7,
    'users_rated' => 167,
    'from' => 'Manila',
    'to' => 'Puerto Princesa',
    'price' => 22500,
    'original_price' => 28000,
    'start_date' => 'July 5, 2025',
    'end_date' => 'July 20, 2025',
    'trip_id' => '214238735',
    'activities' => ['kayaking', 'hiking', 'fishing'],
    'info_needs' => ['transportation', 'health', 'gear', 'political']
  ],
  [
    'image' => '/assets/destinations/baguio.jpg',
    'package' => 'Baguio Cool Escape',
    'location' => 'Baguio City',
    'url' => '/details/baguio',
    'country' => 'Philippines',
    'star' => 3,
    'rating' => 8.9,
    'users_rated' => 134,
    'from' => 'Manila',
    'to' => 'Baguio',
    'price' => 8500,
    'original_price' => 11000,
    'start_date' => 'August 1, 2025',
    'end_date' => 'August 5, 2025',
    'trip_id' => '214238736',
    'activities' => ['hiking', 'mountain_biking'],
    'info_needs' => ['transportation', 'weather', 'gear']
  ],
  [
    'image' => 'assets/bohol.webp',
    'package' => 'Bohol Chocolate Hills Tour',
    'location' => 'Bohol, Panglao Island',
    'url' => '/details/bohol',
    'country' => 'Philippines',
    'star' => 4,
    'rating' => 9.3,
    'users_rated' => 178,
    'from' => 'Manila',
    'to' => 'Tagbilaran',
    'price' => 16900,
    'original_price' => 21000,
    'start_date' => 'September 10, 2025',
    'end_date' => 'September 20, 2025',
    'trip_id' => '214238737',
    'activities' => ['kayaking', 'fishing', 'hiking'],
    'info_needs' => ['transportation', 'weather', 'health']
  ],
  [
    'image' => '/assets/destinations/bangkok.jpg',
    'package' => 'Bangkok Cultural Journey',
    'location' => 'Bangkok',
    'url' => '/details/bangkok',
    'country' => 'Thailand',
    'star' => 4,
    'rating' => 9.1,
    'users_rated' => 245,
    'from' => 'Manila',
    'to' => 'Bangkok',
    'price' => 28500,
    'original_price' => 35000,
    'start_date' => 'October 5, 2025',
    'end_date' => 'October 12, 2025',
    'trip_id' => '214238738',
    'activities' => ['hiking'],
    'info_needs' => ['transportation', 'health', 'political']
  ],
  [
    'image' => '/assets/destinations/tokyo.jpg',
    'package' => 'Tokyo Winter Experience',
    'location' => 'Tokyo',
    'url' => '/details/tokyo',
    'country' => 'Japan',
    'star' => 5,
    'rating' => 9.6,
    'users_rated' => 312,
    'from' => 'Manila',
    'to' => 'Tokyo',
    'price' => 45000,
    'original_price' => 55000,
    'start_date' => 'November 15, 2025',
    'end_date' => 'November 25, 2025',
    'trip_id' => '214238739',
    'activities' => ['skiing', 'hiking'],
    'info_needs' => ['transportation', 'weather', 'gear', 'political']
  ],
  [
    'image' => '/assets/destinations/newport.jpg',
    'package' => 'Newport Beach California',
    'location' => 'Newport Beach, Los Angeles',
    'url' => '/details/newport',
    'country' => 'United States',
    'star' => 5,
    'rating' => 9.4,
    'users_rated' => 198,
    'from' => 'Manila',
    'to' => 'Los Angeles',
    'price' => 75000,
    'original_price' => 90000,
    'start_date' => 'June 15, 2025',
    'end_date' => 'June 25, 2025',
    'trip_id' => '214238740',
    'activities' => ['surfing', 'fishing', 'kayaking'],
    'info_needs' => ['transportation', 'weather', 'gear', 'political']
  ],
  [
    'image' => '/assets/destinations/upper-hutt.jpg',
    'package' => 'Upper Hutt Nature Retreat',
    'location' => 'Upper Hutt',
    'url' => '/details/upper-hutt',
    'country' => 'New Zealand',
    'star' => 4,
    'rating' => 9.0,
    'users_rated' => 87,
    'from' => 'Manila',
    'to' => 'Wellington',
    'price' => 68000,
    'original_price' => 82000,
    'start_date' => 'February 10, 2025',
    'end_date' => 'February 24, 2025',
    'trip_id' => '214238741',
    'activities' => ['hiking', 'mountain_biking', 'fishing'],
    'info_needs' => ['transportation', 'weather', 'gear', 'activity']
  ],
  [
    'image' => '/assets/destinations/wyoming.jpg',
    'package' => 'Wyoming Winter Wilderness',
    'location' => 'Wyoming',
    'url' => '/details/wyoming',
    'country' => 'United States',
    'star' => 5,
    'rating' => 9.8,
    'users_rated' => 124,
    'from' => 'Manila',
    'to' => 'Jackson Hole',
    'price' => 82000,
    'original_price' => 98000,
    'start_date' => 'December 5, 2025',
    'end_date' => 'December 15, 2025',
    'trip_id' => '214238742',
    'activities' => ['skiing', 'hiking', 'fishing', 'mountain_biking'],
    'info_needs' => ['transportation', 'weather', 'gear', 'health', 'activity']
  ]
];

$random_people = [
  'assets/random-people/1.jpg',
  'assets/random-people/2.jpg',
  'assets/random-people/3.jpg',
  'assets/random-people/4.jpg',
  'assets/random-people/5.jpg',
];

$logos = [
  'assets/logos/1.jpg',
  'assets/logos/2.jpg',
  'assets/logos/3.png',
  'assets/logos/4.png',
  'assets/logos/5.webp',
];
